services:
  - type: web
    name: ze-fashion-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node migrate.js && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true

